version: 2
updates:
  - package-ecosystem: npm
    directory: "/"
    schedule:
      interval: "weekly"
      day: "monday"
      time: "08:00"
      timezone: "Europe/Warsaw"
    open-pull-requests-limit: 5
    ignore:
      - dependency-name: "next"
        update-types: ["version-update:semver-major"]
