version: 2
updates:
  - package-ecosystem: "npm"
    directory: "/"
    schedule:
      interval: "monthly"
      day: "monday"
      time: "07:00"
      timezone: "Europe/Warsaw"
    open-pull-requests-limit: 5
    groups:
      minor-and-patch-updates:
        update-types:
          - "minor"
          - "patch"
